[package]
name = "nfc-writer"
version = "0.1.0"
description = "Desktop NFC Writer mit 3D-UI"
authors = ["Fabian López Lange"]
edition = "2021"

[lib]
name = "nfc_writer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
